version: '3.1'

services:

  mongo:
    image: mongo:4.2.2
    restart: always
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - mongodbdata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      
volumes:
  mongodbdata: